# NumPy

* Numerical Python의 약자

* 다양한 수학 연산과 다차원 데이터를 쉽게 다루기 위한 파이썬 라이브러리

* Numpy는 ndarray라고 하는 특별한 객체를 사용
    + 리스트와 달리 고정된 크기를 갖음
    + 같은 타입의 데이터만 저장 가능

* ndarray는 python 리스트에서 지원하지 않는 다양한 기능들을 지원
    + 효율적으로 코드 작성 가능
    + 더 빠른 속도

In [1]:
import numpy as np



---



# 배열 생성

## 리스트로 배열 만들기
![1.2 Array.png](https://drive.google.com/uc?id=1EKPVGuDQinETf6XkcKFYaQfqp5P2oklE)

In [2]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1])

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2


In [3]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)
print(type(a2))
print(a2.shape)
print(a2[0, 0], a2[1, 1])

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
1 5


In [4]:
a3 = np.array([[[1, 2, 3, 0], [4, 5, 6, 0], [7, 8, 9, 0]],
       [[1, 2, 3, 0], [4, 5, 6, 0], [7, 8, 9, 0]]])
print(a3)
print(a3.shape)

[[[1 2 3 0]
  [4 5 6 0]
  [7 8 9 0]]

 [[1 2 3 0]
  [4 5 6 0]
  [7 8 9 0]]]
(2, 3, 4)


## 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `ones()`: 모든 요소를 1로 초기화

In [6]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

* `full()`: 모든 요소를 지정한 값으로 초기화

In [7]:
np.full((2, 3), 2)

array([[2, 2, 2],
       [2, 2, 2]])

* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [8]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

* `tri()`: 삼각행렬 생성

In [9]:
np.tri(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [10]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [11]:
print(a2.shape)
np.zeros_like(a2)

(2, 3)


array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
print(a1.shape)
np.ones_like(a1)

(5,)


array([1, 1, 1, 1, 1])

In [13]:
print(a3.shape)
np.full_like(a3, 10)

(2, 3, 4)


array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]])

## 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [14]:
np.arange(0, 30, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

* `linspace()`: 범위 내에서 균등 간격의 배열 생성

In [15]:
np.linspace(1, 30, 10)

array([ 1.        ,  4.22222222,  7.44444444, 10.66666667, 13.88888889,
       17.11111111, 20.33333333, 23.55555556, 26.77777778, 30.        ])

## 랜덤값으로 배열 생성

| 함수 | 설명 |
|------|------|
| `seed` | 난수 발생을 위한 시드(seed) 지정 |
| `permutation` | 순서를 임의로 바꾸거나 임의의 순열 반환 |
| `shuffle` | 리스트나 배열의 순서를 뒤섞음 |
| `random` | 랜덤한 수의 배열 생성 |
| `rand` | 균등분포에서 표본 추출 |
| `randint` | 주어진 최소/최대 범위의 난수 추출 |
| `randn` | 표준편차가 1, 평균값 0인 정규분포의 표본 추출 |
| `binomial` | 이항분포에서 표본 추출 |
| `normal` | 정규분포(가우시안)에서 표본 추출 |
| `beta` | 베타분포에서 표본 추출 |
| `chisquare` | 카이제곱분포에서 표본 추출 |
| `gamma` | 감마분포에서 표본 추출 |
| `uniform` | 균등(0, 1)분포에서 표본 추출 |

* `random.random()`: 랜덤한 수의 배열 생성

In [16]:
np.random.random((3, 3))

array([[0.28729121, 0.19294703, 0.30106703],
       [0.91240661, 0.6977268 , 0.47116864],
       [0.8309958 , 0.01238427, 0.21510558]])

* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [17]:
np.random.randint(0, 10, (3, 3))

array([[7, 2, 4],
       [8, 7, 7],
       [1, 7, 9]])

* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [18]:
np.random.normal(2, 1, (3,3))

array([[0.84494915, 3.95450504, 2.14727379],
       [1.56888896, 1.43396851, 2.75049056],
       [2.6189741 , 1.86559198, 2.08382328]])

* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [19]:
np.random.rand(3)

array([0.45244492, 0.2780124 , 0.80999065])

* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [20]:
np.random.randn(2,5)

array([[-1.61494059, -1.11243399,  0.30491287, -0.71841899,  1.08808079],
       [-0.83575125,  1.68068361,  0.44261391, -0.01800451, -0.78355195]])

## 표준 데이터 타입

| 데이터 타입	    | 설명 |
|---------------|-------------|
| ``bool_``     | 바이트로 저장된 불리언(Boolean)으로 True 또는 False 값을 가짐 |
| ``int_``      | 기본 정수(Integer) 타입 | 
| ``intc``      | C 언어에서 사용되는 ``int``와 동일 (일반적으로 ``int32`` 또는 ``int64``) | 
| ``intp``      | 인덱싱에 사용되는 정수 (C 언어에서 ``ssize_t``와 동일; 일반적으로 ``int32`` 또는 ``int64``) | 
| ``int8``      | 바이트(Byte) (-128 ~ 127) | 
| ``int16``     | 정수 (-32768 ~ 32767) |
| ``int32``     | 정수 (-2147483648 ~ 2147483647) |
| ``int64``     | 정수(-9223372036854775808 ~ 9223372036854775807) | 
| ``uint8``     | 부호 없는 정수 (0 ~ 255) | 
| ``uint16``    | 부호 없는 정수 (0 ~ 65535) | 
| ``uint32``    | 부호 없는 정수 (0 ~ 4294967295) | 
| ``uint64``    | 부호 없는 정수 (0 ~ 18446744073709551615) |  
| ``float16``   | 반정밀 부동 소수점(Half precision float): 부호 비트, 5비트 지수, 10비트 가수 | 
| ``float32``   | 단정밀 부동 소수점(Single precision float): 부호 비트, 8비트 지수, 23비트 가수| 
| ``float64``   | 배정밀 부동 소수점(Double precision float): 부호 비트, 11비트 지수, 52비트 가수 |
| ``float_``    | ``float64``를 줄여서 표현 |
| ``complex64`` | 복소수(Complex number), 두 개의 32비트 부동 소수점으로 표현 | 
| ``complex128``| 복소수, 두 개의 64비트 부동 소수점으로 표현| 
| ``complex_``  | ``complex128``를 줄여서 표현 | 

In [21]:
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [22]:
np.ones((2,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [23]:
np.full((3,2), 2, dtype=float)

array([[2., 2.],
       [2., 2.],
       [2., 2.]])



---



# 배열 조회

## 배열 속성 정보

In [24]:
def array_info(arr):
    print(arr)
    print('ndim:', arr.ndim)           # 차원 속성의 수
    print('shape:', arr.shape)
    print('dtype:', arr.dtype)
    print('size:', arr.size)           # 요소의 개수
    print('itemsize:', arr.itemsize)   # byte로 반환
    print('nbytes:', arr.nbytes)       # 메모리 사이즈
    print('strides:', arr.strides)     # 등간격: 차원과 차원 사이의 간격

In [25]:
array_info(a1)

[1 2 3 4 5]
ndim: 1
shape: (5,)
dtype: int32
size: 5
itemsize: 4
nbytes: 20
strides: (4,)


In [26]:
array_info(a2)

[[1 2 3]
 [4 5 6]]
ndim: 2
shape: (2, 3)
dtype: int32
size: 6
itemsize: 4
nbytes: 24
strides: (12, 4)


In [27]:
array_info(a3)

[[[1 2 3 0]
  [4 5 6 0]
  [7 8 9 0]]

 [[1 2 3 0]
  [4 5 6 0]
  [7 8 9 0]]]
ndim: 3
shape: (2, 3, 4)
dtype: int32
size: 24
itemsize: 4
nbytes: 96
strides: (48, 16, 4)


## 인덱싱(Indexing)

## 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [28]:
print(a1[::-2])

[5 3 1]


In [29]:
print(a3)
print(a3[1])
print(a3[::-1,1: , ::])

[[[1 2 3 0]
  [4 5 6 0]
  [7 8 9 0]]

 [[1 2 3 0]
  [4 5 6 0]
  [7 8 9 0]]]
[[1 2 3 0]
 [4 5 6 0]
 [7 8 9 0]]
[[[4 5 6 0]
  [7 8 9 0]]

 [[4 5 6 0]
  [7 8 9 0]]]


## 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [31]:
print(a1)
bi = [False, True, False, True, True] # a1과 같은 크기
print(a1[bi])
bi = [True, False, True, False, True]
print(a1[bi])

[1 2 3 4 5]
[2 4 5]
[1 3 5]


In [36]:
print(a2)
bi = np.random.randint(0, 2, (2, 3), dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]]
[[False False False]
 [ True False  True]]
[4 6]




---



# 배열 값 삽입/수정/삭제/복사

## 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [37]:
print(a1)
b1 = np.insert(a1, 0, 10)
print(b1)
c1 = np.insert(a1, 2, 10)
print(c1)

[1 2 3 4 5]
[10  1  2  3  4  5]
[ 1  2 10  3  4  5]


In [41]:
print(a2)
b2 = np.insert(a2, 1, 10, axis=0)
print(b2)
c2 = np.insert(a2, 1, 10, axis=1)
print(c2)

print(a2.shape, b2.shape, c2.shape)

[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]]
[[ 1 10  2  3]
 [ 4 10  5  6]]
(2, 3) (3, 3) (2, 4)


## 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

In [42]:
a1[0] = 11
a1[1] = 22
a1[2] = 33
print(a1)

[11 22 33  4  5]


In [43]:
a1[:2] = 9
print(a1)

[ 9  9 33  4  5]


In [44]:
i = np.array([1, 3, 4])
a1[i] = 0
print(a1)

[ 9  0 33  0  0]


In [47]:
a2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
a2[2, 2] = 0
a2[1] = 0
a2

array([[1, 2, 3],
       [0, 0, 0],
       [7, 8, 0]])

In [50]:
a2[1:, 1:] = 1
a2

array([[1, 2, 3],
       [0, 1, 1],
       [7, 1, 1]])

## 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [52]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)

[1 2 3 4 5]


In [54]:
b1 = np.delete(a1, 1)
print(b1)
print(a1)

[1 3 4 5]
[1 2 3 4 5]


In [56]:
a2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
c2 = np.delete(a2, 1, axis=1)
print(c2)

[[1 3]
 [4 6]
 [7 9]]


## 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [59]:
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
a2_sub = a2[:2, :2] # a2를 바꾸면 a2_sub도 바뀜
print(a2_sub)

[[1 2]
 [4 5]]



* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [62]:
a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy)

[[1 2]
 [4 5]]




---



# 배열 변환

## 배열 전치 및 축 변경

In [63]:
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [64]:
print(a2.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [65]:
print(a2.swapaxes(1, 0))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


## 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [66]:
n1 = np.arange(1, 11)
print(n1)
print(n1.reshape(5, 2))

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [73]:
print(a2.reshape(1, 9))

[[1 2 3 4 5 6 7 8 9]]


In [67]:
print(n1)

[ 1  2  3  4  5  6  7  8  9 10]


* `newaxis()`: 새로운 축 추가. 한 차원 증가

In [68]:
print(n1[np.newaxis, 2:5])
print(n1[2:5, np.newaxis])

[[3 4 5]]
[[3]
 [4]
 [5]]


## 배열 크기 변경

* `resize()`: 배열 크기 변경
* element의 수가 같으면, 배열 모양만 변경
* element의 sequence는 유지됨

In [75]:
n1.resize(2, 5)
print(n1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


* resize 크기가 원본 배열보다 크면, 남은 공간은 0으로 채워짐

In [76]:
n1.resize(5, 5) #(Version Up) refcheck=False
print(n1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]


* resize 크기가 원본 배열보다 작으면, 기본 값은 삭제됨

In [77]:
n1.resize(2,4)
print(n1)

[[1 2 3 4]
 [5 6 7 8]]


## 배열 추가

* `append()`: 배열의 끝에 값 추가

In [80]:
print(a2, b2, sep='\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [81]:
c2 = np.append(a2, b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9  1  2  3 10 10 10  4  5  6]


* axis를 0으로 지정 : 행 방향 결합

In [82]:
c2 = np.append(a2, b2, axis=0) # 데이터 추가
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 1  2  3]
 [10 10 10]
 [ 4  5  6]]


* axis를 1로 지정 : 열 방향 결합

In [83]:
c2 = np.append(a2, b2, axis=1) # 컬럼 추가
print(c2)

[[ 1  2  3  1  2  3]
 [ 4  5  6 10 10 10]
 [ 7  8  9  4  5  6]]


## 배열 분할

* `split()`: 배열 분할

In [85]:
a1 =np.arange(11, 21)
print(a1)

[11 12 13 14 15 16 17 18 19 20]


In [86]:
b1, c1 = np.split(a1, [5]) # 인덱스부터 분핳
print(b1, c1)

[11 12 13 14 15] [16 17 18 19 20]


* `vsplit()`: 수직(y축) 분할. 행 분할 / 인덱스 기준

In [89]:
a2 = np.arange(1, 13).reshape(3, 4)
print(a2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [90]:
b2, c2 = np.vsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]]


* `hsplit()`: 수평(x축) 분할. 열 분할 / 컬럼 기준

In [91]:
b2, c2 = np.hsplit(a2, [2])
print(b2)
print(c2)

[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]


In [96]:
a, b, c = np.split(a1, [2, 4])
print(a1)
print(a, b, c)

[11 12 13 14 15 16 17 18 19 20]
[11 12] [13 14] [15 16 17 18 19 20]


In [99]:
print(a2)
a, b, c = np.vsplit(a2, [1, 2])
print(a, b, c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]] [[5 6 7 8]] [[ 9 10 11 12]]




---



# 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

## 브로드캐스팅(Broadcasting)

![1.3 Broadcasting.png](https://drive.google.com/uc?id=1iDTSzbR5GILf1-A7aTfNssG_IF6UZAD2)

In [101]:
a1 = np.array([1, 2, 3])
print(a1)
print(a1 + 5)
print(a1 * 5)

[1 2 3]
[6 7 8]
[ 5 10 15]


In [102]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a1 * a2)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


In [106]:
a3 = np.arange(1, 4).reshape(3, 1)
print(a1)
print(a3)
print(a3 * a1)

[1 2 3]
[[1]
 [2]
 [3]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]


## 산술 연산(Arithmetic Operators)

| 연산자	      | 범용 함수           | 설명        |
|---------------|---------------------|-------------|
|``+``          |``np.add``           | 덧셈        |
|``-``          |``np.subtract``      | 뺄셈        |
|``-``          |``np.negative``      | 단항 음수  |
|``*``          |``np.multiply``      | 곱셈        |
|``/``          |``np.divide``        | 나눗셈      |
|``//``         |``np.floor_divide``  | 나눗셈 내림 |
|``**``         |``np.power``         | 지수 연산   |
|``%``          |``np.mod``           | 나머지 연산 |


In [107]:
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [108]:
print(np.mod(a2, 2))

[[1 0 1]
 [0 1 0]
 [1 0 1]]


In [111]:
b1 = np.full((1,3), 2)
print(b1)

[[2 2 2]]


In [113]:
c1 = np.power(b1, a2)
print(c1)

[[  2   4   8]
 [ 16  32  64]
 [128 256 512]]


In [114]:
print(np.negative(c1))

[[  -2   -4   -8]
 [ -16  -32  -64]
 [-128 -256 -512]]


### 절대값 함수(Absolute Function)
* `absolute()`, `abs()`: 내장된 절대값 함수  

### 제곱/제곱근 함수
* `square()`: 제곱 / `sqrt()`: 제곱근 (음수의 경우 N/A)  

### 지수 함수
* `exp(n)`: e^n
* `expa(n)`: a^n
* `power(a, n)`: a^n  

### 로그 함수
* `log()`: 밑(e)
* `loga(b)`: 밑(a)

In [15]:
a1 = [4, 8, 10, 100]
print(a1)
b1 = np.log(a1)
print(b1)
print(np.exp(b1))
print(np.log2(a1))

[4, 8, 10, 100]
[1.38629436 2.07944154 2.30258509 4.60517019]
[  4.   8.  10. 100.]
[2.         3.         3.32192809 6.64385619]


### 집계함수(aggregate Functions)

| 함수	       | NaN 안전모드       | 설명          |
|----------------|--------------------|---------------|
|``np.sum``      |``np.nansum``       | 요소의 합 계산|
|``np.cumsum``   |``np.nancumsum``    | 요소의 누적 합|
|``np.diff``     |N/A                 | 요소의 차분   |
|``np.prod``     |``np.nanprod``      | 요소의 곱 계산|
|``np.cumprod``  |``np.nancumprod``   | 요소의 누적 곱|
|``np.dot``      |N/A                 | 점 곱         |
|``np.matmul``   |N/A                 | 행렬 곱       |
|``np.tensordot``|N/A                 | 텐서 곱       |
|``np.cross``    |N/A                 | 벡터 곱       |
|``np.inner``    |N/A                 | 내적          |
|`np.outer`      |N/A                 | 외적          |
|`np.mean`       |``np.nanmean``      | 요소의 평균 계산|
|`np.std`        |``np.nanstd``       | 표준 편차 계산|
|`np.var`        |``np.nanvar``       | 분산 계산|
|`np.min`        |``np.nanmin``       | 최소값|
|`np.max`        |``np.nanmax``       | 최대값|
|`np.argmin`     |``np.nanargmin``    | 최소값 인덱스|
|`np.argmax`     |``np.nanargmax``    | 최대값 인덱스|
|`np.median`     |``np.nanmedian``    | 중앙값|
|`np.percentile` |``np.nanpercentile``| 요소의 순위 기반 백분위 수 계산|
|`np.any`        |N/A                 | 요소 중 참이 있는지 평가|
|`np.all`        |N/A                 | 모든 요소가 참인지 평가|

* `sum()`: 합 계산

In [18]:
a1 = np.random.randint(1, 10, size=(3, 3))
print(a1)

[[4 7 8]
 [3 4 1]
 [4 1 8]]


In [20]:
print(np.sum(a1), a1.sum())
print('열 방향 합:', np.sum(a1, axis=0))
print('행 방향 합:', np.sum(a1, axis=1))

40 40
열 방향 합: [11 12 17]
행 방향 합: [19  8 13]


* `cumsum()`: 누적합 계산

In [23]:
print(np.cumsum(a1))
print('열 방향 누적:')
print(np.cumsum(a1, axis=0))
print('행 방향 누적:')
print(np.cumsum(a1, axis=1))

[ 4 11 19 22 26 27 31 32 40]
열 방향 누적:
[[ 4  7  8]
 [ 7 11  9]
 [11 12 17]]
행 방향 누적:
[[ 4 11 19]
 [ 3  7  8]
 [ 4  5 13]]


* `prod()`: 곱 계산

In [26]:
print(np.prod(a1))
print('열 방향 곱:', np.prod(a1, axis=0))
print('행 방향 곱:', np.prod(a1, axis=1))

86016
열 방향 곱: [48 28 64]
행 방향 곱: [224  12  32]


* `cumprod()`: 누적곱 계산

In [27]:
print(np.cumprod(a1))
print('열 방향 누적:')
print(np.cumprod(a1, axis=0))
print('행 방향 누적:')
print(np.cumprod(a1, axis=1))

[    4    28   224   672  2688  2688 10752 10752 86016]
열 방향 누적:
[[ 4  7  8]
 [12 28  8]
 [48 28 64]]
행 방향 누적:
[[  4  28 224]
 [  3  12  12]
 [  4   4  32]]


* `dot()`: 점곱
* `matmul()`: 행렬곱 계산 (Matrix Multiply)

In [28]:
print(a1)
b1 = np.ones_like(a1)
print(b1)

[[4 7 8]
 [3 4 1]
 [4 1 8]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [29]:
print(np.dot(a1, b1))
print(np.matmul(a1, b1))

[[19 19 19]
 [ 8  8  8]
 [13 13 13]]
[[19 19 19]
 [ 8  8  8]
 [13 13 13]]


* `mean()`: 평균

In [32]:
print(a1)

[[4 7 8]
 [3 4 1]
 [4 1 8]]


In [31]:
print(np.mean(a1))
print('열 방향 평균:', np.mean(a1, axis=0))

4.444444444444445
열 방향 평균: [3.66666667 4.         5.66666667]


* `std()`: 표준편차

In [33]:
print(np.std(a1))
print('열 방향 표준편차:', np.std(a1, axis=0))

2.543449587168799
열 방향 표준편차: [0.47140452 2.44948974 3.29983165]


* `var()`: 분산

In [34]:
print(np.var(a1))
print('열 방향 분산:', np.var(a1, axis=0))

6.469135802469136
열 방향 분산: [ 0.22222222  6.         10.88888889]


* `min()`: 최소값

In [35]:
print(np.min(a1))
print('열 방향 최소값:', np.min(a1, axis=0))

1
열 방향 최소값: [3 1 1]


* `max()`: 최대값

In [36]:
print(np.max(a1))
print('열 방향 최대값:', np.max(a1, axis=0))

8
열 방향 최대값: [4 7 8]


* `median()`: 중간값

In [37]:
print(np.median(a1))
print('열 방향 중간값:', np.median(a1, axis=0))

4.0
열 방향 중간값: [4. 4. 8.]


### percentile(): 백분위 수

- percentile(a, q, interpolation="linear")
 - a배열 요소의 q번째 백분위 수 계산
 - q는 0~100 사이의 값
 - interpolation: 백분위 수가 두 데이터 i, j (i>j) 사이에 있을 때 사용할 보간 방법
  - 'linear': i + (i-j) * fraction, where fraction is the fractional part of the index surrounded by i and j.
  - 'lower': i
  - 'higher': j
  - 'nearest': i or j, whichever is nearest
  - 'midpoint': (i+j)/2

### any(), all()  
* `any()`: True가 있는지 확인

In [38]:
c1 = np.array([[False, False, False],
              [True, True, True], 
              [False, True, False]])

print(np.any(c1))
print(np.any(c1, axis=0))
print(np.any(c1, axis=1))

True
[ True  True  True]
[False  True  True]


* `all()`: 모두 True인지 확인

In [39]:
print(np.all(c1))
print(np.all(c1, axis=0))
print(np.all(c1, axis=1))

False
[False False False]
[False  True False]


### 비교함수

| 연산자	      | 범용 함수           |
|---------------|---------------------|
|``==``          |``np.equal``           |
|``!=``          |``np.not_equal``      |
|``<``          |``np.less``      |
|``<=``          |``np.less_equal``      |
|``>``          |``np.greater``        |
    |``>=``         |``np.greater_equal``  |

## 정렬  
### 전체 정렬  
* `np.sort(array)`: 정렬된 배열의 복사본 생성. 원본 배열의 변경 없음
* `array.sort()`: 원본 배열의 값이 변경됨

In [40]:
arr = np.random.randint(1, 10, size=10)
print(arr)

[1 9 5 7 8 6 8 5 6 3]


In [41]:
print(np.sort(arr))
print(arr)
print(arr.sort())
print(arr)

[1 3 5 5 6 6 7 8 8 9]
[1 9 5 7 8 6 8 5 6 3]
None
[1 3 5 5 6 6 7 8 8 9]


### 부분정렬  
* `partition(array, k)`: 배열에서 k개의 작은 값을 선택하여 왼쪽에 배치
* `partition(array, -k)`: 배열에서 k개의 큰 값을 선택하여 오른쪽에 배치

In [43]:
arr = np.random.randint(1, 10, 10)
print(arr)
print(np.partition(arr, 3))
print(np.partition(arr, -3))
print(arr)

[8 8 2 3 7 6 3 3 2 1]
[1 2 2 3 3 6 3 7 8 8]
[3 1 2 3 2 6 3 7 8 8]
[8 8 2 3 7 6 3 3 2 1]


## 배열 입출력

|함수	           |설명                                |파일종류     |
|----------------|------------------------------------|-------------|
|``np.save()``   |NumPy 배열 객체 1개를 파일에 저장   |바이너리     |
|``np.savez()``  |NumPy 배열 객체 여러개를 파일에 저장|바이너리     |
|``np.load()``   |NumPy 배열 저장 파일로부터 객체 로딩|바이너리     |
|``np.loadtxt()``|텍스트 파일로부터 배열 로딩         |텍스트       |
|``np.savetxt()``|텍스트 파일에 NumPy 배열 객체 저장  |텍스트       |


# 참고문헌

* NumPy, https://numpy.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly